<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            // Kopi (category_id: 1)
            [
                'category_id' => 1,
                'name' => 'Kopi Robusta Lampung Sinar Baru 250g',
                'slug' => 'kopi-robusta-lampung-sinar-baru-250g',
                'short_description' => 'Kopi robusta pilihan dari perkebunan Lampung Barat.',
                'description' => 'Kopi Robusta Lampung Sinar Baru adalah kopi pilihan yang berasal dari perkebunan kopi terbaik di Lampung Barat. Diproses secara natural untuk menghasilkan cita rasa yang kuat, bold, dan memiliki body yang tebal. Cocok untuk pecinta kopi yang menyukai rasa autentik kopi Lampung. Berat bersih 250 gram.',
                'price' => 45000,
                'original_price' => null,
                'stock' => 150,
                'weight' => 270,
                'rating' => 4.8,
                'review_count' => 234,
                'images' => ['/images/products/kopi-robusta-1.jpg', '/images/products/kopi-robusta-2.jpg'],
                'is_featured' => true,
                'is_sale' => false,
            ],
            [
                'category_id' => 1,
                'name' => 'Kopi Arabika Way Tenong Specialty',
                'slug' => 'kopi-arabika-way-tenong-specialty',
                'short_description' => 'Kopi arabika specialty grade dari Way Tenong, Lampung Barat.',
                'description' => 'Kopi Arabika Way Tenong Specialty adalah kopi single origin berkualitas tinggi dari dataran tinggi Way Tenong. Dengan proses full washed, kopi ini menghasilkan rasa fruity, floral, dan acidity yang cerah. Grade specialty dengan skor cupping di atas 80. Berat bersih 200 gram.',
                'price' => 85000,
                'original_price' => 95000,
                'stock' => 80,
                'weight' => 220,
                'rating' => 4.9,
                'review_count' => 89,
                'images' => ['/images/products/kopi-arabika-1.jpg'],
                'is_featured' => true,
                'is_sale' => true,
            ],
            [
                'category_id' => 1,
                'name' => 'Kopi Lampung Bubuk Premium 500g',
                'slug' => 'kopi-lampung-bubuk-premium-500g',
                'short_description' => 'Kopi bubuk siap seduh, roasting medium-dark.',
                'description' => 'Kopi Lampung Bubuk Premium sudah dihaluskan dan siap diseduh. Proses roasting medium-dark menghasilkan rasa yang seimbang antara pahit dan manis. Cocok untuk tubruk, V60, maupun french press. Berat bersih 500 gram.',
                'price' => 65000,
                'original_price' => null,
                'stock' => 200,
                'weight' => 520,
                'rating' => 4.6,
                'review_count' => 156,
                'images' => ['/images/products/kopi-bubuk-1.jpg'],
                'is_featured' => false,
                'is_sale' => false,
            ],

            // Makanan (category_id: 2)
            [
                'category_id' => 2,
                'name' => 'Keripik Pisang Coklat Premium',
                'slug' => 'keripik-pisang-coklat-premium',
                'short_description' => 'Keripik pisang renyah dengan lapisan coklat premium.',
                'description' => 'Keripik Pisang Coklat Premium dibuat dari pisang kepok pilihan yang diiris tipis dan digoreng renyah, kemudian dilapisi coklat premium Belgium. Tekstur renyah di luar dan lumer di mulut. Tersedia dalam kemasan 250 gram, cocok untuk oleh-oleh keluarga.',
                'price' => 25000,
                'original_price' => 35000,
                'stock' => 300,
                'weight' => 270,
                'rating' => 4.7,
                'review_count' => 512,
                'images' => ['/images/products/keripik-pisang-1.jpg', '/images/products/keripik-pisang-2.jpg'],
                'is_featured' => true,
                'is_sale' => true,
            ],
            [
                'category_id' => 2,
                'name' => 'Lempok Durian Asli',
                'slug' => 'lempok-durian-asli',
                'short_description' => 'Dodol durian tradisional khas Lampung.',
                'description' => 'Lempok Durian Asli dibuat dari buah durian lokal Lampung yang diolah secara tradisional tanpa pengawet. Tekstur lembut dan legit dengan aroma durian yang kuat. Setiap bungkus berisi 300 gram lempok yang dikemas rapi.',
                'price' => 50000,
                'original_price' => null,
                'stock' => 100,
                'weight' => 320,
                'rating' => 4.5,
                'review_count' => 178,
                'images' => ['/images/products/lempok-durian-1.jpg'],
                'is_featured' => true,
                'is_sale' => false,
            ],
            [
                'category_id' => 2,
                'name' => 'Sambal Lampung Bajak Kenacan Kaca',
                'slug' => 'sambal-lampung-bajak-kenacan',
                'short_description' => 'Sambal bajak pedas manis khas Lampung dalam jar kaca.',
                'description' => 'Sambal Lampung Bajak Kenacan dibuat dari cabai rawit dan cabai merah pilihan, diulek kasar dengan bumbu rempah tradisional Lampung. Disajikan dalam jar kaca premium 200 gram. Tahan hingga 3 bulan tanpa pengawet buatan.',
                'price' => 38000,
                'original_price' => 45000,
                'stock' => 250,
                'weight' => 350,
                'rating' => 4.6,
                'review_count' => 203,
                'images' => ['/images/products/sambal-lampung-1.jpg'],
                'is_featured' => false,
                'is_sale' => true,
            ],
            [
                'category_id' => 2,
                'name' => 'Keripik Pisang Asin Original Lampung',
                'slug' => 'keripik-pisang-asin-original',
                'short_description' => 'Keripik pisang asin gurih renyah khas Lampung.',
                'description' => 'Keripik pisang asin original dibuat dari pisang kepok segar yang diiris tipis dan digoreng hingga renyah sempurna. Rasa gurih dan asin pas, tanpa MSG. Kemasan 200 gram.',
                'price' => 20000,
                'original_price' => null,
                'stock' => 400,
                'weight' => 220,
                'rating' => 4.4,
                'review_count' => 321,
                'images' => ['/images/products/keripik-asin-1.jpg'],
                'is_featured' => false,
                'is_sale' => false,
            ],
            [
                'category_id' => 2,
                'name' => 'Kemplang Panggang Ikan Tenggiri',
                'slug' => 'kemplang-panggang-ikan-tenggiri',
                'short_description' => 'Kemplang panggang gurih dari ikan tenggiri segar.',
                'description' => 'Kemplang Panggang Ikan Tenggiri khas Lampung, dibuat dari ikan tenggiri segar pilihan. Dipanggang dengan arang kelapa untuk aroma smoky yang khas. Renyah dan gurih, cocok sebagai camilan atau lauk. Kemasan 150 gram.',
                'price' => 30000,
                'original_price' => null,
                'stock' => 180,
                'weight' => 170,
                'rating' => 4.3,
                'review_count' => 145,
                'images' => ['/images/products/kemplang-1.jpg'],
                'is_featured' => false,
                'is_sale' => false,
            ],

            // Kerajinan (category_id: 3)
            [
                'category_id' => 3,
                'name' => 'Kain Tapis Motif Pucuk Rebung',
                'slug' => 'kain-tapis-motif-pucuk-rebung',
                'short_description' => 'Kain tapis tenun tangan dengan motif pucuk rebung tradisional.',
                'description' => 'Kain Tapis Motif Pucuk Rebung adalah kain tenun tangan asli suku Lampung dengan motif tradisional pucuk rebung yang melambangkan kehidupan dan pertumbuhan. Ditenun oleh pengrajin lokal menggunakan benang emas dan sutra. Ukuran 200cm x 80cm. Cocok untuk koleksi, hiasan dinding, atau busana adat.',
                'price' => 175000,
                'original_price' => 200000,
                'stock' => 25,
                'weight' => 350,
                'rating' => 4.8,
                'review_count' => 67,
                'images' => ['/images/products/tapis-1.jpg', '/images/products/tapis-2.jpg'],
                'is_featured' => true,
                'is_sale' => true,
            ],
            [
                'category_id' => 3,
                'name' => 'Tas Anyam Tapis Lampung Eksklusif',
                'slug' => 'tas-anyam-tapis-lampung-eksklusif',
                'short_description' => 'Tas anyam eksklusif dengan sentuhan kain tapis Lampung.',
                'description' => 'Tas Anyam Tapis Lampung Eksklusif menggabungkan teknik anyaman rotan dengan aksen kain tapis tradisional. Didesain modern namun tetap mempertahankan unsur budaya Lampung. Ukuran 30cm x 25cm x 12cm, dilengkapi tali kulit sintetis premium.',
                'price' => 120000,
                'original_price' => null,
                'stock' => 40,
                'weight' => 450,
                'rating' => 4.7,
                'review_count' => 43,
                'images' => ['/images/products/tas-anyam-1.jpg'],
                'is_featured' => false,
                'is_sale' => false,
            ],
            [
                'category_id' => 3,
                'name' => 'Miniatur Siger Lampung Kuningan',
                'slug' => 'miniatur-siger-lampung-kuningan',
                'short_description' => 'Miniatur mahkota Siger dari kuningan berkualitas.',
                'description' => 'Miniatur Siger Lampung dibuat dari bahan kuningan berkualitas tinggi dengan finishing polish mengkilap. Siger adalah mahkota adat Lampung yang melambangkan kehormatan dan kemuliaan. Tinggi 15cm, lebar 20cm. Ideal sebagai souvenir atau hiasan meja.',
                'price' => 95000,
                'original_price' => null,
                'stock' => 60,
                'weight' => 500,
                'rating' => 4.5,
                'review_count' => 78,
                'images' => ['/images/products/siger-1.jpg'],
                'is_featured' => false,
                'is_sale' => false,
            ],

            // Minuman (category_id: 4)
            [
                'category_id' => 4,
                'name' => 'Teh Herbal Serai Merah Lampung 30 Sachet',
                'slug' => 'teh-herbal-serai-merah-lampung',
                'short_description' => 'Teh herbal dari serai merah organik Lampung.',
                'description' => 'Teh Herbal Serai Merah Lampung dibuat dari serai merah organik yang tumbuh di dataran tinggi Lampung Barat. Kaya antioksidan dan membantu menjaga kesehatan tubuh. Isi 30 sachet celup siap seduh. Tanpa pewarna dan pengawet buatan.',
                'price' => 32000,
                'original_price' => null,
                'stock' => 220,
                'weight' => 180,
                'rating' => 4.4,
                'review_count' => 92,
                'images' => ['/images/products/teh-serai-1.jpg'],
                'is_featured' => false,
                'is_sale' => false,
            ],
            [
                'category_id' => 4,
                'name' => 'Kopi Arabika Way Tenong Cold Brew 250ml',
                'slug' => 'kopi-arabika-cold-brew-250ml',
                'short_description' => 'Cold brew arabika siap minum, brewing 16 jam.',
                'description' => 'Cold Brew dari kopi Arabika Way Tenong yang di-brew selama 16 jam pada suhu rendah. Menghasilkan rasa smooth, less acidic, dan natural sweetness. Siap minum dalam kemasan botol kaca 250ml. Simpan di kulkas, tahan 7 hari.',
                'price' => 28000,
                'original_price' => null,
                'stock' => 100,
                'weight' => 350,
                'rating' => 4.6,
                'review_count' => 56,
                'images' => ['/images/products/cold-brew-1.jpg'],
                'is_featured' => false,
                'is_sale' => false,
            ],

            // Souvenir (category_id: 5)
            [
                'category_id' => 5,
                'name' => 'Gantungan Kunci Siger Lampung',
                'slug' => 'gantungan-kunci-siger-lampung',
                'short_description' => 'Gantungan kunci berbentuk Siger, bahan akrilik premium.',
                'description' => 'Gantungan Kunci Siger Lampung terbuat dari akrilik premium dengan desain detail mahkota Siger. Ringan, tahan lama, dan cocok sebagai souvenir khas Lampung. Ukuran 5cm x 4cm. Tersedia dalam pilihan warna emas dan perak.',
                'price' => 15000,
                'original_price' => null,
                'stock' => 500,
                'weight' => 30,
                'rating' => 4.2,
                'review_count' => 312,
                'images' => ['/images/products/gantungan-kunci-1.jpg'],
                'is_featured' => false,
                'is_sale' => false,
            ],
            [
                'category_id' => 5,
                'name' => 'Kaos Oleh-oleh Lampung Siger Edition',
                'slug' => 'kaos-olehlampung-siger-edition',
                'short_description' => 'Kaos cotton combed 30s dengan desain Siger Lampung.',
                'description' => 'Kaos Oleh-oleh Lampung Siger Edition dibuat dari bahan cotton combed 30s yang nyaman dan adem. Desain eksklusif motif Siger dan landmark Lampung. Sablon DTF berkualitas tinggi yang awet dan tidak mudah luntur. Tersedia ukuran S, M, L, XL.',
                'price' => 89000,
                'original_price' => null,
                'stock' => 150,
                'weight' => 250,
                'rating' => 4.5,
                'review_count' => 198,
                'images' => ['/images/products/kaos-1.jpg'],
                'is_featured' => false,
                'is_sale' => false,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
